DB : "data/processed/us_concatenated.extxyz"
TOP : "data/unprocessed/us_0nm.gro"
TRAJ : "data/unprocessed/us_concatenated.xtc" 
REACTIVE_SELECTION : "index 24 59 529" 
RESULTS_DIR : "src/chemtraj/results/us/"
